matrix:
  include:
  - language: node_js
    node_js:
      - "stable"
    sudo: required
    services:
      - docker
    before_install:
      - cd client
    before_script:
      - wget -qO- https://cli-assets.heroku.com/install.sh | sh
      - npm install
    cache: 
      directories:
        - client/node_modules
    script:
      - npm test
      - npm run build
      - docker build -t fluffy-risk-client .
    after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker tag fluffy-risk-client $DOCKER_USER/fluffy-risk-client:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USER/fluffy-risk-client:$TRAVIS_BUILD_NUMBER
      - docker tag fluffy-risk-client $DOCKER_USER/fluffy-risk-client:latest
      - docker push $DOCKER_USER/fluffy-risk-client:latest
      - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
      - /usr/local/bin/heroku container:login
      - docker tag fluffy-risk-client registry.heroku.com/fluffy-risk-client/web
      - /usr/local/bin/heroku container:push web registry.heroku.com/fluffy-risk-client/web
      - /usr/local/bin/heroku container:release web -a fluffy-risk-client


  - language: go
    go:
      - master
    before_install:
      - cd server
    script:
      - go test -v ./...
    
on:
  branch: development
notifications:
  email:
    - arsainos@gmail.com