matrix:
  include:
  - language: node_js
    node_js:
      - "stable"
    sudo: required
    services:
      - docker
    before_install:
      - cd client
    before_script:
      - wget -qO- https://cli-assets.heroku.com/install.sh | sh
      - sudo apt-get install expect
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - expect heroku_login_script.exp $HEROKU_CREDENTIALS_EMAIL $HEROKU_CREDENTIALS_PASSWORD
      - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
      - npm install
    cache: 
      directories:
        - client/node_modules
    script:
      - npm test
      - docker build -t fluffy-risk-client .
    deploy:
      provider: script
      script:
        # push to dockerhub and heroku
        - docker tag fluffy-risk-client $DOCKER_USER/fluffy-risk-client:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USER/fluffy-risk-client:$TRAVIS_BUILD_NUMBER
        - docker tag fluffy-risk-client $DOCKER_USER/fluffy-risk-client:latest
        - docker push $DOCKER_USER/fluffy-risk-client:latest
        - heroku container:login
        - docker tag fluffy-risk-client registry.heroku.com/fluffy-risk-client/web
        - docker push registry.heroku.com/fluffy-risk-client/web
        - heroku container:release web -a fluffy-risk-client

  - language: go
    go:
      - master
    before_install:
      - cd server
    script:
      - go test -v ./...
    
on:
  branch: development
notifications:
  email:
    - arsainos@gmail.com