matrix:
  include:
  - language: node_js
    node_js:
      - "stable"
    before_install:
      - cd client
    cache: 
      directories:
        - client/node_modules
    script:
      - npm test
      - npm run build
on:
  branch: development
notifications:
  email:
    - arsainos@gmail.com