matrix:
  include:
  - language: node_js
    node_js:
      - "stable"
    cache:
      directories:
        - node_modules
    before_script:
      - cd client
    script:
      - npm test
      - npm run build
on:
  branch: development
notifications:
  email:
    - arsainos@gmail.com