matrix:
  include:
  - language: node_js
    node_js:
      - "stable"
    before_install:
      - cd client
    cache: 
      directories:
        - client/node_modules
    script:
      - npm test
      - npm run build

  - language: go
    go:
      - release
    before_install:
      - cd server
    script:
      - go test -v ./...
    
on:
  branch: development
notifications:
  email:
    - arsainos@gmail.com