version: '3.4'

services: 
    clients-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - GRPC_PORT=81
            - PORT=80
        ports:
            - "5103:80"
            - "9103:81"

    identity-api:
        ports: 
            - "32771:80"
            - "32772:443"